apiCategories = [
	"Constructor",
	"Deconstructor",
	"Method",
	"Math Operations"
]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
url = "https://probablytukars.github.io"
baseUrl = "/LuaQuaternion"