name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: binaries/ubuntu/luau tests/test.luau
      - name: Build code
        run: binaries/ubuntu/lua54 tests/build.lua
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install moonwave
        run: npm i -g moonwave

      - name: Create documentation
        run: |
          git config --global user.email 
          moonwave build --publish

        
