name: CI/CD
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: binaries/ubuntu/luau tests/test.luau
      - name: Build code
        run: binaries/ubuntu/lua54 tests/build.lua
      - name: Push changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name "github-actions-bot"
            git config --global user.email "support+actions@github.com"
            git add .
            git commit -m "[action] - Build luau files"
            git push
          else
            echo "WARNING: No changes were detected. git commit push action aborted."
          fi
          
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
      
      - name: Generate JSON from Luau
        run: python docs/luaujson.py
        
      - name: Generate HTML from JSON
        run: python docs/htmlgen.py
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build'
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      
      
