name: CI/CD
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  Integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: binaries/ubuntu/luau tests/test.luau
      - name: Build code
        run: binaries/ubuntu/lua54 tests/build.lua
  Deployment:
    permissions:
      pages: write
      id-token: write
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      
