name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: binaries/ubuntu/luau tests/test.luau
      - name: Build code
        run: binaries/ubuntu/lua54 tests/build.lua
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: moonwave
        run: |
          npm i -g moonwave
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "support+actions@github.com"
          git config --global user.name "github-actions-bot"
          moonwave build --publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
